//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerLiveStatus.dbo_connt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServersMonetory
    {
        public int Id { get; set; }
        public string ServerName { get; set; }
        public Nullable<System.TimeSpan> Seprator91 { get; set; }
        public Nullable<System.TimeSpan> Seprator95 { get; set; }
        public Nullable<System.TimeSpan> Seprator100 { get; set; }
        public Nullable<System.TimeSpan> Seprator98 { get; set; }
        public Nullable<System.TimeSpan> ElmeasureSeprator { get; set; }
        public Nullable<System.TimeSpan> NeptuneSeprator { get; set; }
        public Nullable<System.TimeSpan> LogixSeprator { get; set; }
        public Nullable<System.TimeSpan> PesaurdinoSeprator { get; set; }
        public Nullable<System.TimeSpan> PesDcuSeprator { get; set; }
        public Nullable<System.TimeSpan> Disconnection91 { get; set; }
        public Nullable<System.TimeSpan> Disconnection95 { get; set; }
        public Nullable<System.TimeSpan> Disconnection100 { get; set; }
        public Nullable<System.TimeSpan> Disconnection98 { get; set; }
        public Nullable<System.TimeSpan> DisconnectionElmeasure { get; set; }
        public Nullable<System.TimeSpan> DisconnectionNeptune { get; set; }
        public Nullable<System.TimeSpan> DisconnectionLogix { get; set; }
        public Nullable<System.TimeSpan> DisconnectionPasaurdino { get; set; }
        public Nullable<System.TimeSpan> DisconnectionPesDcu { get; set; }
        public Nullable<System.TimeSpan> MeterSock91 { get; set; }
        public Nullable<System.TimeSpan> MeterSock95 { get; set; }
        public Nullable<System.TimeSpan> MeterSock98 { get; set; }
        public Nullable<System.TimeSpan> MeterSock100 { get; set; }
        public Nullable<System.TimeSpan> SmsEngine { get; set; }
    }
}
